if(singleplayer == true){
	draw_set_halign(fa_center)
	draw_set_valign(fa_middle)
	draw_set_font(f_text2)
	draw_set_color(c_red)
	draw_text(room_width/2, room_height/2, "Game Over, No more Energy")
	draw_set_font(f_text)
	draw_text(room_width/2, room_height/2 + 50, "Final Score: " + string(global.score_points))
	draw_text(room_width/2, room_height/2 + 100, "Press R to Restart")
	draw_text(room_width/2, room_height/2 + 150, "Press M to go to Main Menu")
} else if(player1 == true) {
	draw_set_halign(fa_center)
	draw_set_valign(fa_middle)
	draw_set_font(f_text2)
	draw_set_color(c_red)
	draw_text(room_width/2, room_height/2, "Game Over, Red Player Survived")
	draw_set_font(f_text)
	draw_text(room_width/2, room_height/2 + 50, "Blue Player Score: " + string(global.score_points))
	draw_text(room_width/2, room_height/2 + 80, "Red Player Score: " + string(global.score_points2))
	draw_text(room_width/2, room_height/2 + 130, "Press R to Restart")
	draw_text(room_width/2, room_height/2 + 180, "Press M to go to Main Menu")
}else if(player2 == true) {
	draw_set_halign(fa_center)
	draw_set_valign(fa_middle)
	draw_set_font(f_text2)
	draw_set_color(c_red)
	draw_text(room_width/2, room_height/2, "Game Over, Blue Player Survived")
	draw_set_font(f_text)
	draw_text(room_width/2, room_height/2 + 50, "Blue Player Score: " + string(global.score_points))
	draw_text(room_width/2, room_height/2 + 80, "Red Player Score: " + string(global.score_points2))
	draw_text(room_width/2, room_height/2 + 130, "Press R to Restart")
	draw_text(room_width/2, room_height/2 + 180, "Press M to go to Main Menu")
}